server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296


# eureka:
#   client:
#     fetch-registry: true
#     register-with-eureka: true

#   instance:
#     prefer-ip-address: true
#     service-url:
#       defaultZone: http://localhost:8761/euraka


